### ISSUE TITLE
Expense Group Creation

### ISSUE THREAD

**Issue by Anuoluwatobi** [chingu-voyages/v51-tier2-team-28#22]
**As a** User
 **I need** to create a group
 **So that** I can split my expenses
   
 ### Details and Assumptions
 * Group ID is automatically generated and immutable
 * Request the user to input the group name
 * Request user to input group description
 * Prompt user to set budget 
 
 ### Acceptance Criteria  
   
 ```gherkin
 Given that the user wants to create a group 
 When he created the group 
 Then the group is assigned a group ID

**Comment by singhalex** [comment]
3
