### ISSUE TITLE
Upload receipt

### ISSUE THREAD

**Issue by Anuoluwatobi** [chingu-voyages/v51-tier2-team-28#29]
**As a** User
 **I need** to upload receipts 
 **So that** I can have proof of payments
   
 ### Details and Assumptions
 * An expense has already been created 
 * Receipts can be accessed on the groups and expenses. 
 * Create a Firebase cloud storage 
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given that I make a payment 
 When I upload a receipt 
 Then it will be visible in the group&expense level and stored on Firebase 
 ```

**Comment by singhalex** [comment]
3
