### ISSUE TITLE
Analytics 2

### ISSUE THREAD

**Issue by Anuoluwatobi** [chingu-voyages/v51-tier2-team-28#77]
**As a** User
 **I need** to know how much I am owed
 **So that** I can recover the incurred expense

 ### Details and Assumptions
 * An expense group has been created
 * A budget has been set
 * Expenses have been incurred
 *  #35
 * A pie chart the shows how much each friend owes
 * A list of how much each person owes
 * Display the total amount owed. 

 ### Acceptance Criteria  
   
 ```gherkin
 Given that expenses have been incurred
 When I want to know how much each person owes 
 Then I can see a visual presentation of that

**Comment by belunatic** [comment]
5 point
