### ISSUE TITLE
Expense Group PRO MAX update

### ISSUE THREAD

**Issue by Anuoluwatobi** [chingu-voyages/v51-tier2-team-28#78]
**As a** User
 **I need** to see an expense group summary 
 **So that** I can see the status of the group in one glance

 ### Details and Assumptions
 * An expense group has been created
 * Expenses have been incurred
 * #35
 * Provide a summary view that shows the total group expense and individual balance (debt) of each friend 

 ### Acceptance Criteria  
   
 ```gherkin
 Given that expenses have been incurred
 When I want to see how the money is spent
 Then I can see a visual presentation of that

**Comment by belunatic** [comment]
3 point
